include:
  - project: 'project-version3/erp-infra/gitlab-ci'
    file:
      - 'sonarqube-check.yml'
      - 'build-image.yml'
      - 'deploy-image.yml'
      - 'importmap-shared-deps.yml'

stages:
  - test
  - build
  - deploy
  - reconfig

before_script:
  - >
    if [ "$CI_COMMIT_BRANCH" == "uat" ]; then 
      cp $ENV_UAT .env
    else
      cp $ENV .env
    fi
